name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v1.2.1
      with:
        version: 1.27.0
        github-token: ${{ github.token }}
        only-new-issues: 0
